"""create phrase table

Revision ID: d820b0120a6a
Revises: 
Create Date: 2025-06-01 19:54:07.294643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd820b0120a6a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phrase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('phrase', sa.String(length=255), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phrase_id'), 'phrase', ['id'], unique=False)
    op.create_index(op.f('ix_phrase_uuid'), 'phrase', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phrase_uuid'), table_name='phrase')
    op.drop_index(op.f('ix_phrase_id'), table_name='phrase')
    op.drop_table('phrase')
    # ### end Alembic commands ###
